// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TelegramPartHook.Domain.SeedWork;
using TelegramPartHook.Infrastructure.Persistence;

#nullable disable

namespace TelegramPartHook.Infrastructure.Migrations
{
    [DbContext(typeof(BotContext))]
    [Migration("20220804200117_Init")]
    partial class Init
    {
    }
}
