// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TelegramPartHook.Domain.Aggregations.InstagramCacheAggregation;
using TelegramPartHook.Domain.SeedWork;
using TelegramPartHook.Infrastructure.Persistence;

#nullable disable

namespace TelegramPartHook.Infrastructure.Migrations
{
    [DbContext(typeof(BotContext))]
    [Migration("20250104175441_AddNewConfigTable")]
    partial class AddNewConfigTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TelegramPartHook.Domain.Aggregations.CacheAggregation.SearchCache", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<SheetSearchResult[]>("results")
                        .HasColumnType("jsonb")
                        .HasColumnName("results");

                    b.Property<string>("term")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("term");

                    b.HasKey("id");

                    b.ToTable("search", "public");
                });

            modelBuilder.Entity("TelegramPartHook.Domain.Aggregations.ConfigAggregation.Config", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("MinutesToClean")
                        .HasColumnType("integer")
                        .HasColumnName("minutestoclean");

                    b.Property<DateTime>("NextDateSearchOnInstagram")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("nextdatesearchoninstagram");

                    b.Property<DateTime>("NextDateToCacheClear")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("nextdatetocacheclear");

                    b.Property<DateTime>("NextDateToMonitorRun")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("nextdatetomonitorrun");

                    b.HasKey("id");

                    b.ToTable("config", "public");
                });

            modelBuilder.Entity("TelegramPartHook.Domain.Aggregations.ConfigAggregation.ConfigNew", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("id");

                    b.HasIndex("Name");

                    b.ToTable("config_new", "public");
                });

            modelBuilder.Entity("TelegramPartHook.Domain.Aggregations.InstagramCacheAggregation.InstagramCache", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("EndCursor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("endcursor");

                    b.Property<long>("GraphqlId")
                        .HasColumnType("bigint")
                        .HasColumnName("graphqlid");

                    b.Property<InstagramItem[]>("Items")
                        .HasColumnType("jsonb")
                        .HasColumnName("items");

                    b.Property<string>("PageName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pagename");

                    b.HasKey("id");

                    b.ToTable("instacache", "public");
                });

            modelBuilder.Entity("TelegramPartHook.Domain.Aggregations.UserAggregation.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("Repertoire")
                        .HasColumnType("jsonb")
                        .HasColumnName("repertoire");

                    b.Property<string>("activetokens")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("activetokens");

                    b.Property<string>("culture")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("en")
                        .HasColumnName("culture");

                    b.Property<string>("fullname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fullname");

                    b.Property<bool>("isvip")
                        .HasColumnType("boolean")
                        .HasColumnName("isvip");

                    b.Property<string>("lastsearchdate")
                        .HasColumnType("text")
                        .HasColumnName("lastsearchdate");

                    b.Property<int>("searchescount")
                        .HasColumnType("integer")
                        .HasColumnName("searchescount");

                    b.Property<string>("searchesok")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("searchesok");

                    b.Property<string>("searchesscheduled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("searchesscheduled");

                    b.Property<string>("telegramid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("telegramid");

                    b.Property<bool>("unsubscribe")
                        .HasColumnType("boolean")
                        .HasColumnName("unsubscribe");

                    b.Property<string>("vipinformation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("vipinformation");

                    b.HasKey("id");

                    b.ToTable("client", "public");
                });

            modelBuilder.Entity("TelegramPartHook.Infrastructure.Models.AppError", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("Content")
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.HasKey("id");

                    b.ToTable("apperror", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
