//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelegramPartHook.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TelegramPartHook.Domain.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search aborted successfully..
        /// </summary>
        internal static string AbortedSuccessfully {
            get {
                return ResourceManager.GetString("AbortedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to repertoire.
        /// </summary>
        internal static string AddRepertoireViaTelegram {
            get {
                return ResourceManager.GetString("AddRepertoireViaTelegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting conversion....
        /// </summary>
        internal static string BeginningConversion {
            get {
                return ResourceManager.GetString("BeginningConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, I can&apos;t download this audio right now. Try again later!.
        /// </summary>
        internal static string CannotDownloadVideo {
            get {
                return ResourceManager.GetString("CannotDownloadVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose which remember you would like to remove:.
        /// </summary>
        internal static string ChoseRemember {
            get {
                return ResourceManager.GetString("ChoseRemember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm the remember *&apos;{0}&apos;* exclusion?.
        /// </summary>
        internal static string ConfirmRememberExclusion {
            get {
                return ResourceManager.GetString("ConfirmRememberExclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contribute with my music sheets.
        /// </summary>
        internal static string Contribute {
            get {
                return ResourceManager.GetString("Contribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download last search as PDF.
        /// </summary>
        internal static string DownloadAsPDF {
            get {
                return ResourceManager.GetString("DownloadAsPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to define a remember for the search &apos;{0}&apos; now. Try again later!.
        /// </summary>
        internal static string FailedToDefineRemember {
            get {
                return ResourceManager.GetString("FailedToDefineRemember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow us on Instagram!.
        /// </summary>
        internal static string FollowUsInstagram {
            get {
                return ResourceManager.GetString("FollowUsInstagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May I suggest some searches? Click in some bellow button.
        /// </summary>
        internal static string HereSomeSuggestions {
            get {
                return ResourceManager.GetString("HereSomeSuggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade to VIP.
        /// </summary>
        internal static string MakeMeVIP {
            get {
                return ResourceManager.GetString("MakeMeVIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message sent to admin successfully!.
        /// </summary>
        internal static string MessageSuccessfullySentToAdmin {
            get {
                return ResourceManager.GetString("MessageSuccessfullySentToAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor if something appears.
        /// </summary>
        internal static string MonitorForMe {
            get {
                return ResourceManager.GetString("MonitorForMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am sorry {0}, I did not find anything! If your search has accent, please try without it! Doubts? Message us.
        /// </summary>
        internal static string NotFoundMessage1 {
            get {
                return ResourceManager.GetString("NotFoundMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry {0}, nothing here! Check if you typed correctly. If you put the artist name, try search without it!.
        /// </summary>
        internal static string NotFoundMessage2 {
            get {
                return ResourceManager.GetString("NotFoundMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouch {0}, no success 😕\nIf there is some contribution from your side, send it to us..
        /// </summary>
        internal static string NotFoundMessage3 {
            get {
                return ResourceManager.GetString("NotFoundMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry {0}, 0 results for your search!\nThere it goes a tip: does either the song or the artist has accent on its name? If yes, try put it! :).
        /// </summary>
        internal static string NotFoundMessage4 {
            get {
                return ResourceManager.GetString("NotFoundMessage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not a VIP user. To get this privilege, perform the following PIX and then send a message to {0}.\n\nCopy-paste code 👇🏾.
        /// </summary>
        internal static string NotVipUser {
            get {
                return ResourceManager.GetString("NotVipUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed successfully..
        /// </summary>
        internal static string OperationFinalized {
            get {
                return ResourceManager.GetString("OperationFinalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey {0}! I was looking here and seems that I found some results for your search  &apos;{1}&apos; from {2}!\n\nI&apos;ll send it to you now 👇🏾.
        /// </summary>
        internal static string RememberFound {
            get {
                return ResourceManager.GetString("RememberFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already reached out the free remembers amount. Consider becoming a VIP member to have unlimited remembers\n\nPay the above PIX and then send a message to {0}.\n\nTo manage your reminders, send /lembretes.
        /// </summary>
        internal static string RememberNumberExceeded {
            get {
                return ResourceManager.GetString("RememberNumberExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember *{0}* successfully removed!.
        /// </summary>
        internal static string RememberSuccessfullyRemoved {
            get {
                return ResourceManager.GetString("RememberSuccessfullyRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember for the search &apos;{0}&apos; successfully registered!\nTo manage your reminders, send /lembretes.
        /// </summary>
        internal static string ReminderDefined {
            get {
                return ResourceManager.GetString("ReminderDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It isn&apos;t a music sheet.
        /// </summary>
        internal static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File reported successfully. Thanks for your contribution!.
        /// </summary>
        internal static string ReportedSuccessfully {
            get {
                return ResourceManager.GetString("ReportedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching... (If I don&apos;t response in 1 minute or more, search it again!).
        /// </summary>
        internal static string SearchingMessage1 {
            get {
                return ResourceManager.GetString("SearchingMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On the search! Hold on! (If I don&apos;t response in 1 minute or more, search it again!).
        /// </summary>
        internal static string SearchingMessage2 {
            get {
                return ResourceManager.GetString("SearchingMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching! Warming the engines... (If I don&apos;t response in 1 minute or more, search it again!).
        /// </summary>
        internal static string SearchingMessage3 {
            get {
                return ResourceManager.GetString("SearchingMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for suggestion &apos;{0}&apos;....
        /// </summary>
        internal static string SearchingSuggestion {
            get {
                return ResourceManager.GetString("SearchingSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See my benefits.
        /// </summary>
        internal static string SeeMyVIPBenefits {
            get {
                return ResourceManager.GetString("SeeMyVIPBenefits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To manage your reminders, send /lembretes\n\nSee you!.
        /// </summary>
        internal static string SeeYou {
            get {
                return ResourceManager.GetString("SeeYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then send your message (or click /cancelar).
        /// </summary>
        internal static string SendAdminMessage {
            get {
                return ResourceManager.GetString("SendAdminMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send request or suggestion.
        /// </summary>
        internal static string SendSuggestion {
            get {
                return ResourceManager.GetString("SendSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success! Thanks for use our services. I hope that is being useful for you and your friends. If want to support us, please consider do a PIX for our key: *rrnazario@gmail.com* :).
        /// </summary>
        internal static string SuccessMessage1 {
            get {
                return ResourceManager.GetString("SuccessMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success! Thanks for use our services. I hope that is being useful for you and your friends. Follow us on Instagram, click on the button bellow..
        /// </summary>
        internal static string SuccessMessage2 {
            get {
                return ResourceManager.GetString("SuccessMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There it is! I hope that the results being whose you have expected! If want to support us, please consider do a PIX for our key: *rrnazario@gmail.com*.
        /// </summary>
        internal static string SuccessMessage3 {
            get {
                return ResourceManager.GetString("SuccessMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There you go! I hope that the results being whose you have expected! If want to support us, please consider do a PIX for our key: *rrnazario@gmail.com*.
        /// </summary>
        internal static string SuccessMessage4 {
            get {
                return ResourceManager.GetString("SuccessMessage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done! I hope that the results being whose you have expected! Follow us on Instagram, click on the button bellow. :).
        /// </summary>
        internal static string SuccessMessage5 {
            get {
                return ResourceManager.GetString("SuccessMessage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t set any reminders so far..
        /// </summary>
        internal static string ThereAreNoRemembers {
            get {
                return ResourceManager.GetString("ThereAreNoRemembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} this audio is too big and sadly I can&apos;t help you on this..
        /// </summary>
        internal static string TooLongVideo {
            get {
                return ResourceManager.GetString("TooLongVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You searched for a too small term. Try searching a bigger one..
        /// </summary>
        internal static string TooSmallTerm {
            get {
                return ResourceManager.GetString("TooSmallTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get the VIP information. Send a message to {0}..
        /// </summary>
        internal static string UnableSendVIPInfo {
            get {
                return ResourceManager.GetString("UnableSendVIPInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay ;(\n\nSuccessfully unsubscribed..
        /// </summary>
        internal static string Unsubscribed {
            get {
                return ResourceManager.GetString("Unsubscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready {0}! There it is the mp3 of the song *{1}* 👇🏾.
        /// </summary>
        internal static string VideoDownloaded {
            get {
                return ResourceManager.GetString("VideoDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will send {0} files. Send */abortar* to cancel..
        /// </summary>
        internal static string WarningManyMessages {
            get {
                return ResourceManager.GetString("WarningManyMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At the moment, we are under maintenance. Try again later..
        /// </summary>
        internal static string WeAreUnderMaintenance {
            get {
                return ResourceManager.GetString("WeAreUnderMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the VIP plan {0}!\nFirst of all thank you very much for trusting our work.\nClick the button to see all your benefits..
        /// </summary>
        internal static string WelcomeToVip {
            get {
                return ResourceManager.GetString("WelcomeToVip", resourceCulture);
            }
        }
    }
}
